ARG ROS_DISTRO=jazzy
FROM ros:${ROS_DISTRO}
ARG DOCKER_HOME=/root

LABEL maintainer=""
SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive
ARG ROS_DISTRO

RUN if [ -d "build" ]; then \
  apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key 4B63CF8FDE49746E98FA01DDAD19BAB3CBF125EA;fi

# ZSH setup
WORKDIR /root
RUN  --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  apt-get update && apt-get install -y \
  zsh \
  curl

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN chsh -s $(which zsh)

RUN  --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  apt-get update && apt-get install -y \
  python3-colcon-common-extensions \
  bash-completion \
  python3-mysql.connector \
  python3-pip \
  iputils-ping \
  net-tools \
  tmux \
  wget \
  tmuxinator \
  iproute2 \
  ccache \
  vim \
  lld \
  $(apt list 2>/dev/null | grep '^clangd-[0-9]' | sort -V | tail -n 1 | cut -d'/' -f1) \
  clang-format

RUN  --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  apt-get update && apt-get install -y \
  ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
  ros-${ROS_DISTRO}-rmw-fastrtps-cpp

# Install rosbridge_suite and tf2_web_republisher for web interface connectivity
RUN  --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  apt-get update && apt-get install -y \
  ros-${ROS_DISTRO}-rosbridge-suite \
  ros-${ROS_DISTRO}-rosapi \
  ros-${ROS_DISTRO}-tf2-web-republisher

RUN git clone https://github.com/cykerway/complete-alias /root/complete-alias

ENV COLCON_DEFAULTS_FILE=/root/.colcon/defaults.yaml
# COPY context/config/colcon-defaults.yaml $COLCON_DEFAULTS_FILE

# ENV RCUTILS_COLORIZED_OUTPUT=1
# COPY context/config/tmux.conf /root/.tmux.conf
# COPY context/config/cyclonedds*.xml /root
# COPY context/config/shell_aliases /root/.bash_aliases
# COPY context/config/wait_net_interface.sh /root/wait_net_interface.sh

RUN echo "source /root/complete-alias/complete_alias" >> /root/.bash_completion
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /root/.bashrc
RUN echo ". /etc/bash_completion" >> /root/.bashrc
RUN echo 'complete -F _complete_alias "${!BASH_ALIASES[@]}"' >> /root/.bashrc
RUN echo ". /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash" >> /root/.bashrc
RUN echo "umask 002" >> /root/.bashrc

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.zsh" >> /root/.zshrc
RUN sed -i "/source \$ZSH\/oh-my-zsh\.sh/i\zstyle ':omz:update' mode disabled" /root/.zshrc
RUN echo ". /usr/share/colcon_argcomplete/hook/colcon-argcomplete.zsh" >> /root/.zshrc
RUN echo "source /root/.bash_aliases" >> /root/.zshrc
RUN echo "umask 002" >> /root/.zshrc
RUN echo 'eval "$(register-python-argcomplete3 ros2)"' >> /root/.zshrc

# COPY docker/context/ros_entrypoint.sh /ros_entrypoint.sh
RUN sed -i '/exec "\$@"/i umask 002' /ros_entrypoint.sh
RUN sed -i '/exec "\$@"/i echo "umask = $(umask)"' /ros_entrypoint.sh
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
